accessLevels_modify: Modify available access levels
accessLevel_set: Set other users access level
user_changeEmail: Change other users email address
forums_modify: Modify forums main page
topics_create: Create new forums
topics_modify: Modify a forum
special_avatar: Use moderator avatar colour
users_view: View information about other users
user_suspend: Change a users suspension status
user_hideActivity: Hide all threads and posts by a users
topics_viewHidden: View hidden forums
topicThreads_modify: Modify a thread
post_moderate: Show/hide other users posts
chat_modify: Create and modify chat sessions
notification_create: Send notifications to users
topicThreads_create: Create new threads
post_create: Create new posts
message_create: Participate in chat
preferences_modify: Modify own preferences