accessLevels_modify: Modify available access levels
forums_modify: Modify forums main page
topics_create: Create new forums
topics_modify: Modify a forum
topicThreads_modify: Modify a thread
topicThreads_create: Create new threads
post_create: Create new posts
post_moderate: Show/hide other users posts
preferences_modify: Modify own preferences
users_view: View information about other users
special_avatar: Use moderator avatar colour
accessLevel_set: Set other users access level
user_hideActivity: Hide all threads and posts by a users
user_suspend: Change a users suspension status
user_changeEmail: Change other users email address