accessLevels_modify: Modify access levels
topics_modify: Modify topics
topicThreads_modify: Modify existing topic threads
topicThreads_create: Create topic threads
post_create: Create posts
post_moderate: Show/hide posts
preferences_modify: Modify own preferences
users_view: View information about other users
special_avatar: Use special colour for avatar