# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e42dcb2a7494be0d2b620fcce7a670c712de4ace51dc81d9e08a56344233dc7bcf927a66d2c16b35d14f5b72e0302ba4f6d4f544db50ccd284c77f71b4698309

staging:
  secret_key_base: 27edfd8caacb73e48b2601a57efd834720e9286baf93fbcbbe17615bdd6f6099e4ca29b8a5fb15b95a47ad23aa7f1f55a3a1de5a3b49b84d4c28dc5102f8a80c

test:
  secret_key_base: 908e9e94026a9e8f5d2c6d96849c04b7f58f1ded8e1ebc3f1cc37586594f2f16b20ed0c36fa99b23c69794ade9b782aeb847a388d45567a8aafcf2b5daaafceb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 24d69b9d2ad08d27914eaeb6970ab1fc06e88781ea4167cc2a71dd0e8fb0a8bf8c7f3c295b2f689478825610d45b1a9be9257dd1ba81e699aca6e235a2b40202
